In [52]:
class MeraLR:
    def __init__(self):
        self.m=None
        self.b=None
    def fit(self,x_train,y_train):
        num=0
        den=0
        
        
        for i in range(x_train.shape[0]):
            num=num + (( x_train[i] - x_train.mean())*(y_train[i] - y_train.mean()))
            den=den+ (( x_train[i] - x_train.mean())*(x_train[i] - x_train.mean()))
        self.m=num/den;
        self.b=y_train.mean() - (self.m * x_train.mean())
        print(self.m)
        print(self.b)
                      
        
    def predict(self,x_test):
        pass

In [38]:
import numpy as np
import pandas as pd

In [39]:
df=pd.read_csv('placement.csv')

In [40]:
df.head()

cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [41]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values

In [42]:
x

array([7.19, 7.46, 7.54, 6.42, 7.23, 7.3 , 6.69, 7.12, 6.45, 7.75, 6.82,
       6.38, 6.58, 5.68, 7.91, 7.1 , 6.53, 7.56, 6.93, 7.63, 6.69, 7.43,
       6.76, 6.05, 6.44, 6.28, 7.45, 6.53, 7.23, 6.51, 7.46, 7.66, 5.91,
       6.23, 8.15, 7.48, 6.85, 8.51, 6.58, 7.25, 6.6 , 6.7 , 7.46, 7.85,
       7.88, 6.92, 7.3 , 6.92, 6.29, 8.23, 6.2 , 6.24, 7.53, 6.69, 8.42,
       8.12, 6.93, 7.73, 7.34, 7.7 , 7.94, 7.51, 7.61, 6.22, 6.98, 6.27,
       6.67, 8.04, 6.58, 7.41, 6.98, 6.13, 7.9 , 6.39, 6.16, 6.77, 8.35,
       7.1 , 8.2 , 7.63, 6.87, 7.12, 7.22, 7.38, 5.65, 6.03, 7.19, 6.96,
       6.78, 6.56, 7.61, 7.42, 6.48, 7.  , 7.15, 6.89, 7.09, 7.33, 8.12,
       7.46, 6.56, 6.48, 5.92, 6.44, 6.82, 6.72, 6.59, 7.32, 5.94, 7.23,
       6.96, 6.48, 7.23, 7.24, 6.3 , 7.28, 7.16, 7.11, 6.9 , 7.  , 6.99,
       5.91, 5.97, 6.25, 6.2 , 7.46, 7.16, 6.95, 6.76, 6.81, 5.91, 8.19,
       7.71, 7.65, 6.33, 6.63, 7.28, 5.69, 7.53, 8.09, 6.85, 7.19, 7.66,
       6.32, 6.67, 7.08, 6.75, 6.68, 6.86, 6.81, 8.

In [43]:
y

array([ 26.,  38.,  40.,   8.,  17.,  23.,  11.,  39.,  38.,  94.,  16.,
         7.,  16.,  26.,  43.,  21.,  19.,  22.,  27.,  29.,  47.,  33.,
        54.,  11.,  11.,  58.,   8.,  46.,  19.,  15.,  16.,  44.,  11.,
        27.,   9.,  12.,  16.,   9.,  20.,  17.,  86.,  38.,  71.,  63.,
        55.,  10.,  15.,  46.,  42.,  28.,  18.,  28.,  27.,  33.,  36.,
        15.,  15.,  24.,  43.,  32.,  31.,  86.,  22.,  26.,  52.,  28.,
        31.,  18.,  30.,  44.,  17.,  20.,  19.,  12.,   3.,  56.,  12.,
        28.,  12.,  19.,  46.,  44.,  12.,  20.,  35.,  28.,  22.,  19.,
        39.,  17.,  15.,   6.,  63.,  30.,  21.,  35.,  28.,  52.,  76.,
        23.,  46.,  26.,  22.,  18.,  47.,  12.,  22.,   9.,  10.,  21.,
        31.,  33.,  15.,  10.,  77.,  37.,  21.,   0.,  54.,  39.,  46.,
        27.,  51.,  52.,  30.,  55.,  37.,  23.,  25.,  39.,  53.,  19.,
        18.,  64.,  93.,  47.,  15.,  53.,   8.,   5.,  22.,  18.,  41.,
        33.,  17.,  28.,  22.,  11.,  49.,  58.,  2

In [44]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [45]:
x_train.shape

(800,)

In [46]:
lr=MeraLR()

In [47]:
lr.fit(x_train,y_train)

(800,)


In [49]:
x_train

array([7.57, 5.52, 6.75, 7.71, 5.77, 6.9 , 6.97, 6.4 , 7.12, 7.82, 5.74,
       6.55, 7.46, 7.78, 7.29, 7.  , 6.93, 6.98, 7.34, 7.42, 6.51, 6.59,
       6.01, 7.07, 6.1 , 6.74, 7.61, 6.93, 6.96, 6.87, 7.31, 7.49, 7.24,
       7.08, 6.1 , 6.76, 5.97, 7.11, 6.84, 5.92, 7.2 , 6.22, 6.34, 6.64,
       7.06, 7.21, 7.96, 7.03, 7.22, 7.34, 6.87, 7.32, 7.14, 7.8 , 6.67,
       6.49, 6.31, 7.2 , 6.38, 6.87, 6.94, 7.  , 7.95, 7.46, 6.82, 7.73,
       6.85, 7.  , 7.07, 7.31, 7.37, 5.74, 7.47, 7.52, 7.23, 7.56, 8.29,
       7.16, 7.01, 6.95, 7.31, 6.74, 6.51, 7.41, 7.97, 7.  , 6.22, 8.03,
       6.04, 5.68, 6.9 , 6.57, 6.26, 7.18, 7.03, 6.5 , 6.37, 6.18, 7.49,
       6.81, 7.61, 6.67, 7.16, 6.74, 6.77, 6.48, 6.24, 6.52, 7.33, 7.31,
       7.17, 6.63, 8.21, 7.18, 7.9 , 7.54, 7.23, 6.3 , 7.07, 6.58, 7.19,
       7.98, 6.59, 6.17, 5.94, 6.21, 6.86, 7.3 , 6.52, 6.38, 6.9 , 7.2 ,
       6.87, 7.12, 7.17, 6.28, 7.46, 5.91, 6.63, 7.65, 6.73, 7.31, 5.48,
       6.12, 6.24, 8.04, 7.28, 5.83, 6.55, 7.67, 7.

In [53]:
lr.fit(x_train,y_train)

(800,)
