In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

In [3]:
x,y=load_diabetes(return_X_y=True)

In [4]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
y.shape

(442,)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
rg=LinearRegression()

In [9]:
rg.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred=rg.predict(x_test)

In [11]:
from sklearn.metrics import r2_score

In [12]:
r2_score(y_test,y_pred)

0.42168527523799304

In [13]:
rg.coef_

array([  -38.08495183,  -269.6508565 ,   472.05239354,   393.58642537,
       -1063.42302019,   731.63749571,   147.18793285,    93.514692  ,
         901.19993221,    88.07280044])

In [14]:
rg.intercept_

152.9079026460429

In [15]:
x_train .shape

(353, 10)

In [16]:
  class MeraLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        self.intercept_=betas[0];
        self.coef_=betas[1:]
         
    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_)+self.intercept_
        return y_pred




In [17]:
lr=MeraLR()

In [20]:

lr.fit(x_train,y_train)

In [21]:
x_train.shape

(353, 10)

In [23]:
y_pred=lr.predict(x_test)

In [24]:
r2_score(y_test,y_pred)

0.4216852752379934

In [25]:
lr.coef_

array([  -38.08495183,  -269.6508565 ,   472.05239354,   393.58642537,
       -1063.42302019,   731.63749571,   147.18793285,    93.514692  ,
         901.19993221,    88.07280044])