In [1]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd

In [2]:
x,y=load_diabetes(return_X_y=True)

In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
x_train

array([[ 0.00175052,  0.05068012, -0.00620595, ...,  0.03430886,
         0.01482098,  0.09833287],
       [-0.0382074 ,  0.05068012,  0.07139652, ...,  0.071948  ,
         0.05028067,  0.06933812],
       [ 0.01991321, -0.04464164, -0.04069594, ..., -0.03949338,
        -0.03074792,  0.00306441],
       ...,
       [ 0.04170844,  0.05068012,  0.07139652, ...,  0.03430886,
         0.07340696,  0.08590655],
       [ 0.00538306, -0.04464164,  0.05846277, ..., -0.0763945 ,
        -0.05140387, -0.02593034],
       [ 0.07076875,  0.05068012, -0.01698407, ..., -0.00259226,
        -0.07020936, -0.01764613]])

In [6]:
from sklearn.linear_model import Ridge

In [7]:
reg=Ridge(alpha=0.1,solver='cholesky')

In [8]:
reg.fit(x_train,y_train)

Ridge(alpha=0.1, solver='cholesky')

In [10]:
y_pred=reg.predict(x_test)
r2_score(y_test,y_pred)

0.38934140450750976

In [11]:
reg.coef_

array([  12.91594887, -228.40898096,  546.68190862,  241.82720946,
        -77.35950347, -105.32053428, -199.8907042 ,  144.46705067,
        450.49969303,   79.23386967])

In [12]:
reg.intercept_

152.47329826712655

In [19]:
class MeraRidge:

    def __init__(self,alpha=0.1):
        self.alpha=alpha;
        self.coef_=None
        self.intercep_=None
    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        I=np.identity(x_train.shape[1])
        result=np.linalg.inv(np.dot(x_train.T,x_train) + self.alpha*I ).dot(x_train.T).dot(y_train)
        self.intercept_=result[0]
        self.coef_=result[1:] 
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_
        

In [20]:
reg=MeraRidge()

In [23]:
reg.fit(x_train,y_train)


In [27]:
y_pred=reg.predict(x_test)

In [28]:
r2_score(y_test,y_pred)

0.3893859167642585

In [29]:
reg.coef_

array([  12.91498645, -228.38242753,  546.65449857,  241.85616916,
        -77.366815  , -105.29623742, -199.86017095,  144.47862621,
        450.50062212,   79.1918529 ])

In [30]:
reg.intercept_

152.42989842076474